import Config

# Configure your database
config :tabletap, Tabletap.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "tabletap_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Same database as Tabletap.Repo above — see lib/tabletap/oban_repo.ex.
config :tabletap, Tabletap.ObanRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "tabletap_dev",
  pool_size: 5

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tabletap, TabletapWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "MlQhu9v3njU9Xx56rAAWsf6mfv+gxR369bS0J7wxXOWVLuGpyooInKL/m6SwFcU2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tabletap, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tabletap, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :tabletap, TabletapWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/tabletap_web/router\.ex$"E,
      ~r"lib/tabletap_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tabletap, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Cloak dev key — NOT for production (see runtime.exs for the real one).
# Regenerate any time with:
#   elixir -e 'IO.puts(:crypto.strong_rand_bytes(32) |> Base.encode64())'
config :tabletap, Tabletap.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("5GcxCAF62/hDzxUOn9Q8I2I/4Uwz9XIv24zXFMDLoSQ=")}
  ]

# WaafiPay sandbox — dev-only default (safe to hardcode, it's the
# documented sandbox host, never production — runtime.exs forces a real
# env var for that). A real sandbox merchant account still has to be
# entered per-venue via Manager.PaymentSettingsLive to actually charge
# anything; this alone just lets the adapter boot. The platform_* trio
# (Tabletap.Billing's own merchant account, design-qa.md Q59) is a
# dev-only placeholder for the same reason — nothing in dev actually
# collects a real subscription charge.
config :tabletap, :waafipay,
  api_url: "https://sandbox.waafipay.com/asm",
  webhook_secret: "dev-only-not-a-real-secret",
  platform_merchant_uid: "dev-platform-merchant",
  platform_api_user_id: "dev-platform-api-user",
  platform_api_key: "dev-platform-api-key"

# Dev-only VAPID private key (build-plan.md Feature 20) — pairs with
# the public key in config.exs; real, generated, but never used against
# a real user's browser outside this checkout. Never the prod key,
# which comes from an env var (runtime.exs).
config :web_push_ex, :vapid, private_key: "lTSTKeCYxZ_MFHF69n3pfu6PQITXj78AIXGYbWWJ9DE"
