defmodule TabletapWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :tabletap

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_tabletap_key",
    signing_salt: "eiHt1vDM",
    same_site: "Lax"
  ]

  # :peer_data / :x_headers let LiveViews read the connecting IP for the
  # magic-link send throttle (design-qa.md Q47) — TabletapWeb.RateLimiter
  # prefers x-forwarded-for when present (behind a proxy in prod) and
  # falls back to peer_data locally.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Mobile realtime transport (build-plan.md Feature 23) — the official
  # `phoenix` npm client connects here, joining order:{id}/
  # waiter:{membership_id}/venue:{id}:claim_board/venue:{id}:orders.
  socket "/socket", TabletapWeb.ApiSocket, websocket: true, longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :tabletap,
    gzip: not code_reloading?,
    only: TabletapWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :tabletap
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Only the WaafiPay webhook route reads conn.assigns.raw_body — every
    # other route's conn.params is unaffected (TabletapWeb.CacheBodyReader).
    body_reader: {TabletapWeb.CacheBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TabletapWeb.Router
end
